{
 "title": "Ecowitt Weather Station",
 "description": "Ecowitt exporter",
 "tags": [
  "weather",
  "ecowitt"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "station",
    "query": {
     "query": "label_values(ecowitt_temp, station)"
    }
   },
   {
    "name": "wind_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, wind_unit)"
    }
   },
   {
    "name": "temperature_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, temperature_unit)"
    }
   },
   {
    "name": "pressure_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, pressure_unit)"
    }
   },
   {
    "name": "rain_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, rain_unit)"
    }
   },
   {
    "name": "distance_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, distance_unit)"
    }
   },
   {
    "name": "irradiance_unit",
    "query": {
     "query": "label_values(ecowitt_exporter_info, irradiance_unit)"
    }
   },
   {
    "name": "soil_moisture",
    "query": {
     "query": "label_values(ecowitt_exporter_info, soil_moisture)"
    }
   },
   {
    "name": "lightning_enabled",
    "query": {
     "query": "label_values(ecowitt_exporter_info, lightning)"
    }
   },
   {
    "name": "air_quality",
    "query": {
     "query": "label_values(ecowitt_exporter_info, air_quality)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_temp{sensor=\"outdoor\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_humidity{sensor=\"outdoor\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_barom{sensor=\"relative\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_windspeed{sensor=\"windspeed\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Rain rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_rain{sensor=~\"rate|rrain_piezo\", station=~\"$station\"}[2m])",
     "legendFormat": "Rain rate"
    }
   ]
  },
  {
   "title": "Sunlight",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_solarradiation{station=~\"$station\"}",
     "legendFormat": "Solar radiation"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "High temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_temp{sensor=\"outdoor\", station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Low temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "ecowitt_temp{sensor=\"outdoor\", station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Max wind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{sensor=\"windspeed\", station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Max wind gust",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{sensor=\"windgust\", station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Current alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 } },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Air temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_temp{sensor=\"outdoor\", station=~\"$station\"}[2m])",
     "legendFormat": "Outdoor"
    },
    {
     "expr": "last_over_time(ecowitt_temp{sensor=\"indoor\", station=~\"$station\"}[2m])",
     "legendFormat": "Indoor"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_humidity{sensor=\"outdoor\", station=~\"$station\"}[2m])",
     "legendFormat": "Outdoor"
    },
    {
     "expr": "last_over_time(ecowitt_humidity{sensor=\"indoor\", station=~\"$station\"}[2m])",
     "legendFormat": "Indoor"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_barom{sensor=\"relative\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Rainfall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "ecowitt_rain{sensor=~\"rate|event|hourly|daily|weekly|monthly|yearly|rrain_piezo|erain_piezo|hrain_piezo|drain_piezo|wrain_piezo|mrain_piezo|yrain_piezo\", station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Rain totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_rain{sensor=~\"event|hourly|daily|weekly|monthly|yearly|total|erain_piezo|hrain_piezo|drain_piezo|wrain_piezo|mrain_piezo|yrain_piezo\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_windspeed{sensor!=\"maxdailygust\", station=~\"$station\"}[2m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Beaufort",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed_beaufort{station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "ecowitt_winddir{station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_winddir{station=~\"$station\"}"
    }
   ]
  },
  { "title": "Sun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "UV index",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_uv{station=~\"$station\"}",
     "legendFormat": "UV index"
    }
   ]
  },
  {
   "title": "Solar irradiation",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "expr": "last_over_time(ecowitt_solarradiation{station=~\"$station\"}[2m])",
     "legendFormat": "Solar irradiation"
    }
   ]
  },
  {
   "title": "Lightning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last strike distance",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "lengthmi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecowitt_lightning{station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Closest strike distance",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "lengthmi" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "min(ecowitt_lightning){station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Daily count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecowitt_lightning_num{station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Last strike",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecowitt_lightning_time * 1000{station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Air quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM2.5",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "expr": "ecowitt_pm25{series=\"realtime\", station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "PM2.5 24-hour average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "expr": "ecowitt_pm25{series=\"avg_24h\", station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Air Quality Index",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecowitt_aqi{station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Soil moisture",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Soil moisture",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ecowitt_soilmoisture{station=~\"$station\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Battery status (WH25, WH26, WH40, WH65)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_batterystatus{station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Battery level (WH57, WH45, PM2.5, Leak)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_batterylevel{station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Battery voltage (WH90, WH80, WH68, Soil)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_batteryvoltage{station=~\"$station\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Forwarding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forward rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ecowitt_forward_total[5m])",
       "legendFormat": "{{url}} total/s"
      },
      {
       "expr": "rate(ecowitt_forward_errors[5m])",
       "legendFormat": "{{url}} errors/s"
      }
     ]
    }
   ]
  }
 ]
}